version: "3.8"

services:
  app:
    image: spelling-bee-server
    command: sh -c "go run /go/src/cmd/spelling-bee/main.go"
    ports:
      - 3000:3000
    working_dir: /go/src
    volumes:
      - ./:/go/src
    environment: 
      ENV: development
    depends_on:
      - "postgres"
  
  postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    volumes:
      - spelling-bee-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: secret
  
volumes:
  spelling-bee-data: